/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb691",
        "on-secondary-fixed": "#001b3d",
        "secondary": "#005db6",
        "on-tertiary-fixed-variant": "#6c391d",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#2d476f",
        "on-primary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#00468c",
        "surface-container-highest": "#d3e4fe",
        "tertiary-container": "#3d1500",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#d6e3ff",
        "secondary-container": "#63a1ff",
        "surface-tint": "#465f88",
        "surface-variant": "#d3e4fe",
        "primary-container": "#002147",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#74777f",
        "secondary-fixed": "#d6e3ff",
        "primary": "#000a1e",
        "secondary-fixed-dim": "#a9c7ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#341100",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#708ab5",
        "on-surface-variant": "#44474e",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#ffdbcb",
        "inverse-primary": "#aec7f6",
        "surface": "#f8f9ff",
        "outline-variant": "#c4c6cf",
        "on-error": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary": "#180500",
        "on-secondary-container": "#00376f",
        "on-tertiary-container": "#b97958",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#aec7f6",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "warning": "#f59e0b",
        "on-warning": "#ffffff",
        "warning-container": "#fef3c7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "4px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "label-mono": ["'JetBrains Mono'", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
