import { 
  FinalReportData, 
  HistoryRecord, 
  OcrData, 
  ValidationData, 
  TamperingData, 
  FaceVerificationData, 
  RiskAssessmentData 
} from '../types/screening';

export const ASSETS = {
  loginBg: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7AIzzFnt-bEy0-sIlDe4v28pvoH322DpQS1lc44948y6_rbmalvHEZhStOZVToqziV4Wh1g2M3TCvqifgtBzyuMw0PtG61Wrx6lDOFdk--fFwsOyIhN9WCQR6fxuiSKGqIjK8Uth943ksfWrLE20mpPnLSj2-OD0OOOzQCP3eXGBebaEmQAKm8nIz6QUPNcpT4nsdYporr0WtZmBuzYc3YVhFinvobb26J6tXXhLo4z9LERl4sY-X',
  logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrPp9rozVkPJFQS9MH4kEGIe3qQAKwa5jw7ilI-Np-ym48-ZzT_uW8qgzefgMSSsCdlxRARsiu5uq-fAalHu4EgQhV9E2LNEQmrCqCgGvaVDArCymv6lOv7G3O8Qab5a_4VMUIour3cyUXWUoEB5P5jV--hmrUVG4DfMaCnW0flyb9Eq6O9BSNgfWWXh80xrbDGDxx4EhQAp5t1TngLt1xozqMfgYiRykbLuYxSh8Hhpgp2NPrloML',
  officerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCr0Mqbj7DZGx8bM_5p-mqe6a_TcHsqWP-CilozndazpQTH-9abw9JL2DGcRLaV9U4GAfgdj4yTC9tGE7vvp5m4KIAfxnboi4cMjMS6auPMcy3_Hp1KEh77SVFC1-1AEJ045EE16bJ84pUrzDYzYEXrKrNZswPBjqZN8hTM4DJqmAfuEWM_49WBHWSLxI4mBdhloNBkD1n3WG_-PAYvhWEipyONkTeJuC_jW6prWU6l0FlzUElS31zD',
  officerVance: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAm6y2UbtdIydBgfhv5T-XJtlLH1Y2WFyzuk4Szm0-HY0_InkUgGyNMXugdJwlRk_CtItgf7fKKrq80joH7rfbote9-N0lesW6xEYGwOvKORyolP0hHQIJJwXNSeBdtD_bBv0m5F3vjmIjxngAHWfXkMYXM8RA_UGSBbbEyE4b_slrLf_7oY6wgxRdj_3wLwRBugaWHxDgAVY-rQZCP04fcaTRhKiWYkrASRXoe-u5mQ3DgKi4lAEyX',
  passportScanOcr: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDP7WGER0P_N8GBc8gpu_VvQ_ueRKdJWCyrpPi5z6OGS0QM4qDVxxqPMvHpK0UJCDNlbJbo21iPwXTbdvKLwO7JqaNfjxSHFBgHfEiANDifLQxJP2VVJLabGuoyG-AtJUlrLSTn8kW_5wbDJTfMUFpfeLr3KUMPBMI41xPlQyYwdKYx5iViMlWUdDnFhZs4c8PvX5bTgMYmOArQ_JPJgnbUAefRE_NHK5SoLlj0NBuyYHed4S-esE_i',
  passportScanValidation: 'https://lh3.googleusercontent.googleusercontent.com/aida-public/AB6AXuA5BVs84G5Crs__D5w_rlSpHlO44KQ3j0Yw4ZuAhevAMK3XBOlFoKWPITNiRO7FInMoF2ujxZRhA2zPQiVtJ9-m_ndqy_v3TiJbHRMMzeFEfbSF9fULnGLExM0vrgKh2e8uePMQdq6nWWSPHYOpW3JhN1MMLaCuVDnlEHLF8DKpfi5u0KxmX9ZrJ_q1NPOm9SYhgfE2E2ucdLFH7sEOwk4MI1FVin4HBsz9VYP9q9ttEEtywnCYlqYK',
  uvFeature: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpFHCGKF_3tWAmRFqyZXZQ9yesE_Jyp5iLYn0qQHI40Nu6AnX62lPwToraTixJCAnmonRlo6SWFTCVTK2gtveIgUJ4PeBVSwiY0dMHYu8xhjYdol_Ybd1ocPTb1bJNxSvl6-Ohkd9e19-hdavkCvlUAGhp7MNHRqNdUtc9DhGlB1-mNv4tUQmInqHdo0dQUTmZA9zyp3TWBdyQcRCHaYEyK9o8yBOTOkYlCYvDMtvQ-0jjc9vi9Sbf',
  hologramFeature: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCw3gy2tzbyEp4zan1iNUrPXRSk2v0ETsNsBBF1rjMDMWpNDwJYrULpSCQQ0GXMbsq6r6EJw1RbNDt_a_05gGuu2ddx3oQmPnp-sylxjmlGeFVQeOhjOLo97QORiIY9ducrq005EGUUAUiLq9OtNtyRrV3MBjBXj9yIk9z4i59Qgeqtjlc9YjvFO_mctczCExn5G-V-W92y0O8ERTjuiWz3hxdtZPQ_2iX2cT6oxEiMiqgX5yFKjigz',
  microprintingFeature: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8E3QM9Od5ML66HKZlWyJX1Om1ROdLSDJrNgwGNgDabZccdf0-W0c61Ds14dT6cM3VQaDfoh-FE7HIcAVPEYGuC2QBz9R22phIE2MQArZKO0vtW8ahaQSBglpLo1RwYCF7UU_9X6QQo7q4YC56kfmKEHL-YWpIHUkuUdtLvAFoFuGsKMjiyGiVCxa43ZucYTWIQLpWDj884NCczhONHAtyi9mdwJhMt4fhWdw-SM85AqnT4L-ivOvY',
  tamperingScan: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBSTK3eTB9gLi6NoJV6dhQ72axrV2laSyqeVQnJ4-uPOdDFwHgRwHobNf1uIWBDBeyo3B2BieXQpi1gpF_Ue9JtCAkyqp5LYO_Sfbs5nGCSYMjHgdtwAV0mgIiN28_9ur6PhHg2RneWigQwgDUNG4bNqKzmMIfpbVY8DIncuWeyWFt4DGF_UFH1orc3i6U3_KWOj7NfBEN1vrgwEohT-99GM79XqZGDFTSReic0O87lEVXtzN65YK_O',
  faceDocPhoto: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAR_Y9v3fjlNvtRCggtTHUh91-iT4Q3SOF5InF6G6l-Wbw7WxZ0H6mh3haLnMvP6f_a94wg3VJDNsZerJwDmDNKt9-nn0UINACBjSpRuoy6yb2wwpbaCHyCl37v7CgqGjFNjkYIqkqUcejXScrnp-Vr-tOGPT5g6BDce7tw7cYxRqW5BgPFiE6i69pY_XxYEbTy5flGkhu6EwX_fFLz4dao9ilX63mk_FPVjmSlunZl7EfV_qnv9Chw',
  faceLivePhoto: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBztDxhv-LdmT_QOcvFJlPf7RC7fYFunAYPFoQFOZkrsIYgFsZ5ieL_IWSe4ssmEf_paajpZSRv--EO8-ApCt1dcWxKB8AUVRPgH3uFunAli3vWBsHXhhjfBiugcnXCNPpWNdCI2ogqFnGx9JsTO4yJNShPoHD-dm3-joih54B1OyxUxYT9MzfL6ZnsiORHQYWgQDVvLjoXCTkco2p7k6RQstUnmQYsTo8uCBtCSNGJJ9p9LDjAEvKQ',
  passengerReportPhoto: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWtlRheZLxM9cW4AMNHYb-dfJKNMNS-8g5ch-TJw0RFL-Y5tpkbQZM6HoKq7AVrbqvdzmSayV4yhTfGs56DgOiPkcoUlr7w25n5oknNyzixTeQCQM7qlzCito5MTnyC3E0vUHfjzFj2IKNHSRGx69B-rWgQcG_h3HgPUmXz3T70hc8L-5BPZYP81Mz0_pVbiyQ49ZgVIGlbEuegh8kPtmeg-UDAl7Cvc2ZNgxuEm2-Fhq1YJ5LYk0L',
  expiredDocScan: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdjgrYpbiPogVN171_vOHicqoPYlSJFO_U_6o4Gyp2ZTtE5s1cyMeRt8PVDZdC4eypOskilceiSJAmBSrDPsoUbh-IIgT4vLlfAjAMOsydY2xO1805iRQ8tY5NLGot0VGEBNKZg-itMDSj20nF-AsKUdd_fg7Z5xlEwwANAn5Wp9bOQvXWqJn5PLmJXd52od4cqNYCxzf8ctdJFxTCKc1ibRyQNLVdCq7gBbTBTV2ipwLbdoFBAadK',
  tamperedDocScan: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCB_D8S6SHMFqckrbXp9aeyi8IbCcOO3nvxOra-4E4XRmDlxl-cdrZmZWNrRkJ9oeWPjxLjHZjU2Fhplb5eL5w27i2wjtumdUguQvVL0Ko0VkvtXKD7lNolgZaUqD86uzYkosovGcgTwWZBlivOgYheyxa6EKi0eJKlD5W9YLM7mNfDRqFdsgNsFHA4-nfFhyud9jbzqtISlIdD8LCi-h_l0zW4YAoezRSqEUvaSYuAf5mLqYdvEJK',
  modifiedVisualAnomaly: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAVAwi72HPJWAGzeEtUDlQDxJJXQ-bfaojaMRGMw1Dyq5RogsmsVm0A5GuWtjqBGIBEXBxEo091euUQ276TcrtsY_THzyKbrO9eB3kiaOXhFc0qEbFEeo9kPTlKwDAi4K0fISITdy5mSwpsP-yADagyBy7vM1XUyFPuuvCchP641HLl_EDsnMCsiaY_Qw9cDcpEEjvbZQczkHx0oIly2JV5SJDZBuShNLxq6NRupt9X_DFTUj2SyO4H',
  modifiedMrzAnomaly: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASkpsVNX3uFEWLmDqqzEx7FumJYi7RVLq1KbQ_AS0NKPpPKebjJisSILXguKPZMtycabikpLwDfuIplHamqqbyr8GXaNplezKUqmf7RcsSastEr_dCgyhpAaZxn8e8bQUUw3R8mp7oeWyPE1ZzNTT4vkmYf_8aBsfmJfYRCvCYH2liCaVdlgp-x1bFh0TnxdWN9rhfzQrRrKbxn8UBpShR3XudlCq3UMZpmYjJUpvE2zuXqn-ZWXPp',
};

// Default Active Screening Data (Workflow)
export const DEFAULT_OCR_DATA: OcrData = {
  surname: { label: 'Surname', value: 'DOE', confidence: 99 },
  givenNames: { label: 'Given Names', value: 'JOHN SMITH', confidence: 98 },
  dateOfBirth: { label: 'Date of Birth', value: '15 OCT 1985', confidence: 100 },
  nationality: { label: 'Nationality', value: 'UTO', confidence: 99 },
  documentNumber: { label: 'Passport No.', value: 'L89B0?2', confidence: 65, isError: true, errorMessage: 'Low confidence read. Please verify.' },
  dateOfExpiry: { label: 'Date of Expiry', value: '14 OCT 2030', confidence: 97 },
  mrzRaw: `P<UTODOE<<JOHN<SMITH<<<<<<<<<<<<<<<<<<<<<<<<<<<\nL89B082<2UTO8510156M3010141<<<<<<<<<<<<<<06`,
  mrzChecksumValid: true,
  overallConfidence: 94,
  documentImage: ASSETS.passportScanOcr,
};

export const DEFAULT_VALIDATION_DATA: ValidationData = {
  documentType: 'Passport (P)',
  issuingState: 'UTO (Utopia)',
  documentNumber: 'A98765432',
  dateOfBirth: '1985-10-24',
  dateOfExpiry: '2030-10-24',
  isExpired: false,
  documentStatus: 'CLEARED',
  securityFeatures: [
    { name: 'UV Fluorophore Pattern', confidence: 99.2, passed: true, image: ASSETS.uvFeature },
    { name: 'OVD / Hologram', confidence: 98.7, passed: true, image: ASSETS.hologramFeature },
    { name: 'Micro-printing Audit', confidence: 99.5, passed: true, image: ASSETS.microprintingFeature },
  ],
  databaseHits: [
    { database: 'Interpol SLTD', result: 'NO HIT', passed: true },
    { database: 'National Registry', result: 'MATCH', passed: true },
    { database: 'Sanctions List', result: 'NO HIT', passed: true },
  ],
  checklist: {
    documentValidity: { passed: true, message: 'Checksums & MRZ formatting passed.' },
    expiryCheck: { passed: true, message: 'Valid until 2030-10-24 (> 6 months)' },
    visaRequirements: { passed: false, warning: true, message: 'Manual review recommended based on itinerary.' },
  },
};

export const DEFAULT_TAMPERING_DATA: TamperingData = {
  probability: 87,
  riskLevel: 'HIGH',
  scanImage: ASSETS.tamperingScan,
  hasAnomalyBox: true,
  findings: [
    {
      id: 'photo-substitution',
      title: 'Photo Substitution Check',
      status: 'failed',
      description: 'Possible photo substitution detected in the top right corner. Inconsistent edge blending.',
      icon: 'face',
    },
    {
      id: 'overlay-detection',
      title: 'Overlay Detection',
      status: 'passed',
      description: 'No physical overlays or lamination tampering detected over critical data fields.',
      icon: 'layers',
    },
    {
      id: 'font-anomalies',
      title: 'Font Anomalies',
      status: 'failed',
      description: 'Kerning inconsistency detected in Date of Birth field. Likely digital alteration.',
      icon: 'text_fields',
    },
    {
      id: 'edge-consistency',
      title: 'Edge Consistency',
      status: 'passed',
      description: 'Document margins align with standard institutional templates.',
      icon: 'border_outer',
    },
  ],
};

export const DEFAULT_FACE_DATA: FaceVerificationData = {
  documentPhoto: ASSETS.faceDocPhoto,
  livePhoto: ASSETS.faceLivePhoto,
  matchScore: 98,
  thresholdMet: true,
  sourceDoc: 'Source: ePassport Chip',
  sourceLive: 'Source: Gate Camera 04',
  liveness: {
    depthMap: 'Verified 3D',
    microMovement: 'Detected',
    textureAnalysis: 'Natural',
    spoofProbability: 1.2,
    passed: true,
  },
  vectors: [
    { name: 'Inter-ocular Distance', matchScore: 95, icon: 'visibility' },
    { name: 'Jawline Topology', matchScore: 92, icon: 'face_6' },
    { name: 'Nodal Points (68)', matchScore: 99, icon: 'fingerprint' },
  ],
};

export const DEFAULT_RISK_ASSESSMENT_DATA: RiskAssessmentData = {
  riskScore: 12,
  riskLevel: 'LOW',
  recommendation: 'Approved',
  aiModelVersion: 'AQ-V4.2 ACTIVE',
  factors: [
    {
      id: 'doc-auth',
      type: 'positive',
      title: 'Document authenticity confirmed',
      description: 'Holographic and UV markers match issuer database templates with 99.8% confidence.',
      logAction: 'VIEW LOG',
    },
    {
      id: 'mrz-minor',
      type: 'warning',
      title: 'Minor MRZ mismatch',
      description: 'Checksum validation passed, but minor character spacing anomaly detected on line 2. Considered non-critical.',
    },
    {
      id: 'face-match',
      type: 'positive',
      title: 'Face match successful',
      description: 'Live capture biometrics match document photo. Liveness detection confirmed.',
      logAction: 'VIEW SCAN',
    },
  ],
};

// 4 Specific Demo Scenarios
export const DEMO_CASES: Record<string, FinalReportData> = {
  'demo-1': {
    screeningId: 'SCR-2024-893X',
    reportDate: '2024-10-24 14:32 UTC',
    stationId: 'T4-ALPHA-09',
    officerName: 'J. Miller',
    officerId: '8832',
    decisionTitle: 'GENUINE',
    riskLevel: 'LOW',
    confidence: 98,
    overallStatus: 'GENUINE',
    demoCaseName: 'Demo 1: Genuine Document',
    passenger: {
      surname: 'KOWALSKI',
      givenNames: 'JAN',
      dob: '14 FEB 1985',
      nationality: 'POL (Poland)',
      flight: 'BA0283',
      destination: 'LHR',
      photo: ASSETS.passengerReportPhoto,
    },
    document: {
      type: 'e-Passport',
      documentNumber: 'AB1234567',
      issueDate: '10 MAY 2020',
      expiryDate: '10 MAY 2030',
      issuingAuthority: 'Masovian Voivode',
      issuingCountry: 'Poland (POL)',
      chipStatus: 'Read Successful',
      mrz: 'P<POLKOWALSKI<<JAN<<<<<<<<<<<<<<<<<<<<<<<<<<<\nAB12345678POL8502146M3005107<<<<<<<<<<<<<<06',
      scanImage: ASSETS.passportScanOcr,
    },
    checklist: {
      ocrCheck: { status: 'Passed', passed: true },
      documentValidation: { status: 'Passed', passed: true },
      tamperingDetection: { status: 'No significant tampering', passed: true },
      faceVerification: { status: 'Match', passed: true },
      documentStatus: { status: 'Valid', passed: true },
    },
  },
  'demo-2': {
    screeningId: 'AUTH-2023-X982',
    reportDate: '2024-10-24 13:15 UTC',
    stationId: 'T4-ALPHA-09',
    officerName: 'K. Smith',
    officerId: '8491',
    decisionTitle: 'EXPIRED',
    riskLevel: 'MEDIUM',
    confidence: 96,
    overallStatus: 'EXPIRED',
    demoCaseName: 'Demo 2: Expired Document',
    passenger: {
      surname: 'THOMPSON',
      givenNames: 'EMMA JANE',
      dob: '03 SEP 1988',
      nationality: 'GBR (United Kingdom)',
      flight: 'AF1680',
      destination: 'CDG',
      photo: ASSETS.passengerReportPhoto,
    },
    document: {
      type: 'Passport',
      documentNumber: 'P83749201',
      issueDate: '10 MAY 2013',
      expiryDate: '10 MAY 2023',
      issuingAuthority: 'HM Passport Office',
      issuingCountry: 'United Kingdom (GBR)',
      chipStatus: 'Read Successful',
      mrz: 'P<GBRTHOMPSON<<EMMA<JANE<<<<<<<<<<<<<<<<<<<<<\nP837492010GBR8809038F2305106<<<<<<<<<<<<<<02',
      scanImage: ASSETS.expiredDocScan,
    },
    checklist: {
      ocrCheck: { status: 'Passed', passed: true },
      documentValidation: { status: 'Passed', passed: true },
      tamperingDetection: { status: 'No significant tampering detected', passed: true },
      faceVerification: { status: 'Match', passed: true },
      documentStatus: { status: 'Expired', passed: false, detail: 'Expiry Check: Failed — document validity period has ended.' },
    },
    criticalFinding: 'The provided document has exceeded its validity period. Validity ended 10 MAY 2023.',
  },
  'demo-3': {
    screeningId: 'AQ-9932-B',
    reportDate: '2024-10-24 14:02 UTC',
    stationId: 'T4-ALPHA-09',
    officerName: 'K. Vance',
    officerId: '884-X9',
    decisionTitle: 'SUSPECTED TAMPERING',
    riskLevel: 'HIGH',
    confidence: 94,
    overallStatus: 'SUSPECTED TAMPERING',
    demoCaseName: 'Demo 3: Tampered Document',
    passenger: {
      surname: 'REZNOV',
      givenNames: 'VIKTOR',
      dob: '28 JUL 1982',
      nationality: 'UTP (Utopia)',
      flight: 'LH450',
      destination: 'FRA',
      photo: ASSETS.passengerReportPhoto,
    },
    document: {
      type: 'Passport',
      documentNumber: 'UT-7782194',
      issueDate: '15 JAN 2021',
      expiryDate: '15 JAN 2031',
      issuingAuthority: 'Ministry of Interior',
      issuingCountry: 'Utopia (UTP)',
      chipStatus: 'Cryptographic Warning',
      mrz: 'P<UTPREZNOV<<VIKTOR<<<<<<<<<<<<<<<<<<<<<<<<<<\nUT77821944UTP8207281M3101158<<<<<<<<<<<<<<04',
      scanImage: ASSETS.tamperedDocScan,
    },
    checklist: {
      ocrCheck: { status: 'Passed', passed: true },
      documentValidation: { status: 'Warning', passed: false, detail: 'Format and MRZ checksum warning' },
      tamperingDetection: { status: 'Potential alteration detected', passed: false, detail: 'Photo/printed-data region shows visual inconsistencies' },
      faceVerification: { status: 'Match', passed: true },
      documentStatus: { status: 'Suspicious', passed: false, detail: 'Global watchlist warning' },
    },
    criticalFinding: 'Photo/printed-data region shows visual inconsistencies. Laminate tampering and altered micro-lines detected.',
  },
  'demo-4': {
    screeningId: 'SCR-2024-MOD-81',
    reportDate: '2024-10-24 15:10 UTC',
    stationId: 'T4-ALPHA-09',
    officerName: 'K. Vance',
    officerId: '884-X9',
    decisionTitle: 'INFORMATION MISMATCH',
    riskLevel: 'HIGH',
    confidence: 91,
    overallStatus: 'INFORMATION MISMATCH',
    demoCaseName: 'Demo 4: Modified Information',
    passenger: {
      surname: 'HARRISON',
      givenNames: 'ALEXANDER',
      dob: '12 MAR 1990',
      nationality: 'USA (United States)',
      flight: 'UA890',
      destination: 'ORD',
      photo: ASSETS.passengerReportPhoto,
    },
    document: {
      type: 'Passport',
      documentNumber: '558902143',
      issueDate: '01 JUN 2019',
      expiryDate: '01 JUN 2029',
      issuingAuthority: 'Department of State',
      issuingCountry: 'United States of America',
      chipStatus: 'Mismatch with Visual Zone',
      mrz: 'P<USAHARRISON<<ALEXANDER<<<<<<<<<<<<<<<<<<<<<\n5589021438USA9003125M2906014<<<<<<<<<<<<<<08',
      scanImage: ASSETS.modifiedVisualAnomaly,
    },
    checklist: {
      ocrCheck: { status: 'Mismatch Detected', passed: false, detail: 'OCR text differs from visual template' },
      documentValidation: { status: 'Failed', passed: false, detail: 'MRZ checksum failure' },
      tamperingDetection: { status: 'Potential alteration detected', passed: false, detail: 'Visual Zone Anomaly' },
      faceVerification: { status: 'Match', passed: true },
      documentStatus: { status: 'Suspicious', passed: false },
    },
    criticalFinding: 'Extracted document information is inconsistent with the expected document data. The MRZ lines do not align algorithmically with the typed visual zone data.',
    visualEvidence: {
      anomalyTitle: 'Visual Zone Anomaly',
      anomalyImage: ASSETS.modifiedVisualAnomaly,
      mrzAnomalyTitle: 'MRZ Checksum Failure',
      mrzAnomalyImage: ASSETS.modifiedMrzAnomaly,
    },
  },
};

// Screening History initial records
export const INITIAL_HISTORY: HistoryRecord[] = [
  {
    id: 'AQ-2024-8931',
    dateTime: '2024-10-19 14:22:05 UTC',
    passengerName: 'Sarah Jenkins',
    documentId: 'P-99238471-US',
    documentType: 'Passport',
    aiRiskScore: 4,
    riskLevel: 'LOW',
    status: 'Approved',
    officerId: '8832',
  },
  {
    id: 'AQ-2024-8930',
    dateTime: '2024-10-19 14:18:33 UTC',
    passengerName: 'Viktor Reznov',
    documentId: 'ID-44X-90021-RU',
    documentType: 'National ID',
    aiRiskScore: 92,
    riskLevel: 'HIGH',
    status: 'Denied',
    officerId: '884-X9',
  },
  {
    id: 'AQ-2024-8929',
    dateTime: '2024-10-19 13:45:12 UTC',
    passengerName: 'Elena Rostova',
    documentId: 'V-773-M-11',
    documentType: 'Visa',
    aiRiskScore: 45,
    riskLevel: 'MEDIUM',
    status: 'Review',
    officerId: '8832',
  },
  {
    id: 'AQ-2024-8928',
    dateTime: '2024-10-19 13:10:00 UTC',
    passengerName: 'Marcus Chen',
    documentId: 'P-1100223-SG',
    documentType: 'Passport',
    aiRiskScore: 2,
    riskLevel: 'LOW',
    status: 'Approved',
    officerId: '8942',
  },
  {
    id: 'AQ-2024-8927',
    dateTime: '2024-10-19 12:40:15 UTC',
    passengerName: 'Dmitri Kovalev',
    documentId: 'P-77218390-RU',
    documentType: 'Passport',
    aiRiskScore: 89,
    riskLevel: 'HIGH',
    status: 'Denied',
    officerId: '884-X9',
  },
  {
    id: 'AQ-2024-8926',
    dateTime: '2024-10-19 12:15:40 UTC',
    passengerName: 'Marco Rossi',
    documentId: 'ID-ITA-492019',
    documentType: 'National ID',
    aiRiskScore: 38,
    riskLevel: 'MEDIUM',
    status: 'Review',
    officerId: '8832',
  },
  {
    id: 'AQ-2024-8925',
    dateTime: '2024-10-19 11:50:22 UTC',
    passengerName: 'Aisha Khan',
    documentId: 'P-GBR-902341',
    documentType: 'Passport',
    aiRiskScore: 3,
    riskLevel: 'LOW',
    status: 'Approved',
    officerId: '8942',
  },
];
